/**
 * The colour maths behind the dark theme, and the rules it has to satisfy.
 *
 * <p>Imported by `generate-dark-palette.mjs`, which writes the palette, and by
 * `src/lib/theme-palette.test.ts`, which fails the build if any ramp in index.css stops meeting the
 * targets. Keeping both on one implementation is the point: a palette that is generated by one set
 * of rules and checked against another is a palette nobody can trust.
 */

// ------------------------------------------------------------------- sRGB <-> OKLCH

const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const linearToSrgb = (c) => (c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055);

export function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
}

function rgbToHex([r, g, b]) {
  const to = (c) =>
    Math.round(Math.min(1, Math.max(0, c)) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}

function rgbToOklab([r, g, b]) {
  const [lr, lg, lb] = [r, g, b].map(srgbToLinear);
  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb);
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb);
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
}

function oklabToRgb([L, a, b]) {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ].map(linearToSrgb);
}

export function hexToOklch(hex) {
  const [L, a, b] = rgbToOklab(hexToRgb(hex));
  let H = (Math.atan2(b, a) * 180) / Math.PI;
  if (H < 0) H += 360;
  return { L, C: Math.hypot(a, b), H };
}

function oklchToRgb({ L, C, H }) {
  const rad = (H * Math.PI) / 180;
  return oklabToRgb([L, C * Math.cos(rad), C * Math.sin(rad)]);
}

const inGamut = (oklch) => oklchToRgb(oklch).every((c) => c >= -0.0005 && c <= 1.0005);

/** Pulls chroma in until the colour fits sRGB, rather than letting it clip to a flat edge. */
function clampChroma({ L, C, H }) {
  if (inGamut({ L, C, H })) return { L, C, H };
  let lo = 0;
  let hi = C;
  for (let i = 0; i < 24; i += 1) {
    const mid = (lo + hi) / 2;
    if (inGamut({ L, C: mid, H })) lo = mid;
    else hi = mid;
  }
  return { L, C: lo, H };
}

export const oklchToHex = (oklch) => rgbToHex(oklchToRgb(clampChroma(oklch)));

const relativeLuminance = (hex) => {
  const [r, g, b] = hexToRgb(hex).map(srgbToLinear);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

export function contrast(a, b) {
  const [x, y] = [relativeLuminance(a), relativeLuminance(b)].sort((m, n) => n - m);
  return (x + 0.05) / (y + 0.05);
}

// ------------------------------------------------------------------------ the curve

export const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

/**
 * Where each step sits in the dark theme.
 *
 * <p>Measured, not invented: these are the mean lightness and chroma of the eleven ramps that were
 * tuned by hand and checked on screen. Generating the rest against the same curve is what stops a
 * new family looking like it came from a different design.
 *
 * <p>The jump from 300 to 400 is deliberate and matches the hand-tuned ramps — 300 is the last
 * decorative step (separators, empty-state glyphs) and 400 is the first that can carry words.
 * Chroma peaks at 500, the vivid marker step, then falls away as the text steps get lighter.
 */
export const PROFILE = {
  50: { L: 0.255, C: 0.046 },
  100: { L: 0.288, C: 0.055 },
  200: { L: 0.364, C: 0.074 },
  300: { L: 0.466, C: 0.097 },
  400: { L: 0.668, C: 0.131 },
  500: { L: 0.725, C: 0.158 },
  600: { L: 0.802, C: 0.115 },
  700: { L: 0.863, C: 0.082 },
  800: { L: 0.912, C: 0.053 },
  900: { L: 0.955, C: 0.028 },
  950: { L: 0.977, C: 0.015 },
};

export const SURFACE = '#131c2e';
export const CANVAS = '#0a1020';

/** Builds one dark ramp from a family's light ramp, keeping its hue and relative saturation. */
export function generateRamp(lightRamp, referenceChroma) {
  const scale = (lightRamp[500]?.C ?? referenceChroma) / referenceChroma;
  const ramp = {};
  for (const step of STEPS) {
    const source = lightRamp[step] ?? lightRamp[900] ?? lightRamp[500];
    ramp[step] = oklchToHex({
      L: PROFILE[step].L,
      C: PROFILE[step].C * scale,
      H: source.H,
    });
  }
  return ramp;
}

/**
 * The rules every dark ramp has to meet, hand-tuned and generated alike.
 *
 * <p>Returns a list of failures, empty when the ramp is sound.
 */
export function validateRamp(family, ramp) {
  const failures = [];
  const check = (label, fg, bg, min) => {
    if (!fg || !bg) return;
    const ratio = contrast(fg, bg);
    if (ratio < min) failures.push(`${family}: ${label} is ${ratio.toFixed(2)}, needs ${min}`);
  };

  // A badge is a tint with text on it, which is how every status and category chip here is built.
  for (const step of [700, 800, 900]) check(`${step} on ${family}-50`, ramp[step], ramp[50], 4.5);

  // Text and icons sitting directly on a card, and on the page behind it.
  for (const step of [600, 700, 800, 900, 950]) {
    check(`${step} on the card`, ramp[step], SURFACE, 4.5);
    check(`${step} on the page`, ramp[step], CANVAS, 4.5);
  }

  // Borders, edge markers and the vivid fill step: the 3:1 bar for things that are not text.
  for (const step of [400, 500]) check(`${step} on the card`, ramp[step], SURFACE, 3);

  /*
   * The tint has to separate from the card it sits on, measured as perceptual lightness rather than
   * as a contrast ratio. Down at this end of the scale the WCAG formula is nearly useless: the
   * eleven hand-tuned tints, every one of which reads correctly on screen, score anywhere between
   * 1.03 and 1.12, because the formula compresses hard near black and takes no account of the hue
   * shift that does half the work. Their lightness above the card is a much tighter 0.017–0.040.
   */
  if (ramp[50]) {
    const separation = hexToOklch(ramp[50]).L - hexToOklch(SURFACE).L;
    if (separation < 0.015) {
      failures.push(`${family}: 50 sits only ${separation.toFixed(3)}L above the card`);
    }
  }

  return failures;
}

/** Parses `--color-<family>-<step>: #rrggbb` declarations out of a chunk of CSS. */
export function parseRamps(css) {
  const ramps = {};
  for (const [, family, step, hex] of css.matchAll(
    /--color-([a-z]+)-(\d+):\s*(#[0-9a-fA-F]{6})/g,
  )) {
    (ramps[family] ??= {})[Number(step)] = hex;
  }
  return ramps;
}

/** The `:root[data-theme='dark']` block of index.css, as text. */
export function darkBlockOf(css) {
  const start = css.indexOf(":root[data-theme='dark']");
  if (start === -1) throw new Error('index.css has no dark block');
  return css.slice(css.indexOf('{', start), css.indexOf('\n}', start));
}
